-- Phase 7 — weekly_briefs.
--
-- One row per user per week. Generated by cron-weekly-synthesis.js
-- on Sunday at 18:00 local. Opus 4.7 with agentic tool-use loop
-- queries the user's data across the week, identifies patterns,
-- and writes the synthesis here.
--
-- Columns:
--   week_start_date     = Monday of the week the brief covers (date only)
--   structured          = the headline/subhead/sections JSONB the UI renders
--   narrative           = long-form text summary (300-800 words)
--   patterns_discovered_ids = array of patterns_discovered.id this run produced
--   tool_calls_log      = debugging — every tool call Claude made + its response
--                         shape. Capped server-side to last 50 calls.
--   model               = which Claude model produced this brief
--   confidence          = 'high' | 'medium' | 'low'
--   generated_at        = wall-clock timestamp
--   prompt_tokens / completion_tokens / total_iterations = telemetry
--
-- One row per (user_id, week_start_date) — re-running for the same
-- week overwrites the previous attempt (upsert).

create table if not exists public.weekly_briefs (
  id                       uuid primary key default gen_random_uuid(),
  user_id                  uuid not null references auth.users(id) on delete cascade,
  week_start_date          date not null,
  generated_at             timestamptz not null default now(),
  model                    text,
  structured               jsonb,
  narrative                text,
  patterns_discovered_ids  uuid[],
  tool_calls_log           jsonb,
  confidence               text check (confidence in ('high','medium','low')),
  status                   text not null default 'ready' check (status in ('processing','ready','failed')),
  failure_reason           text,
  prompt_tokens            integer,
  completion_tokens        integer,
  total_iterations         integer,
  created_at               timestamptz not null default now()
);

create unique index if not exists weekly_briefs_user_week
  on public.weekly_briefs(user_id, week_start_date);

create index if not exists weekly_briefs_user_recent
  on public.weekly_briefs(user_id, week_start_date desc);

alter table public.weekly_briefs enable row level security;
drop policy if exists "weekly_briefs own" on public.weekly_briefs;
create policy "weekly_briefs own" on public.weekly_briefs for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());
